### ISSUE TITLE
Required Port changes

### ISSUE THREAD

**Issue by khakers** [unturned-info/unturned-3-knowledgebase#21]
Unturned recently changed the steam server query port to be the same as the game server port. This means that game server *should* no longer need +2 ports. The Server Hosting and Port Forwarding pages will need to be edited to reflect this.

Unturned update: 
3.21.30.0
https://store.steampowered.com/news/app/304930/view/3058500029563754250

**Comment by kulkaGM** [comment]
If your server port is 27015, then 27016 is still used. So the +1 is still needed.
