### ISSUE TITLE
Port forwarding page still contains refs to three ports

### ISSUE THREAD

**Issue by 06000208** [unturned-info/unturned-3-knowledgebase#64]
In #21 the page on port forwarding was changed to reflect that unturned only uses two ports, but not all text on that page was changed.

![2023-04-06-firefox-1680808137](https://user-images.githubusercontent.com/52764066/230472500-0502c006-08fe-4096-806f-491ac7d35edb.png)
![2023-04-06-firefox-1680808164](https://user-images.githubusercontent.com/52764066/230472566-3b692265-e8de-47d0-9ed5-7b85a2d1b159.png)

**Comment by khakers** [comment]
Thanks for pointing this out. Let me know if I've missed any mentions of the ports in the fix.
